
server:
  port: 8081

spring:
  boot:
    admin:
      client:
        url: http://127.0.0.1:8080
  application:
    name: monitor-client

management:
  endpoints:
    web:
      exposure:
        include: '*'