
server:
  port: 8000

spring:
  application:
    name: 'monitor-eureka'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: '*'